### ISSUE TITLE
Should include babel config in npm

### ISSUE THREAD

**Issue by g1084164986** [popperjs/popper-core#1105]
### CodeSandbox demo

N/A compile issue

### Steps to reproduce the problem

1. packaging popper to other projects and using babel, it will compile node_modules recursive
2. because of package.json include the babel config file path if will try to read it
3. none of config file found, babel will throw an error when compile

just like this

```bash
ERROR in ./node_modules/@popperjs/core/lib/popper.js
Module build failed: Error: [BABEL] D:\workspace\iviewex\node_modules\@popperjs\core\lib\popper.js: Couldn't resolve extends clause of ./.config/babel.config in D:\workspace\iviewex\node_modules\@popperjs\core\package.json
    at Logger.error (D:\workspace\iviewex\node_modules\babel-core\lib\transformation\file\logger.js:41:11)
    at ConfigChainBuilder.mergeConfig (D:\workspace\iviewex\node_modules\babel-core\lib\transformation\file\options\build-config-chain.js:186:32)
    at ConfigChainBuilder.addConfig (D:\workspace\iviewex\node_modules\babel-core\lib\transformation\file\options\build-config-chain.js:157:10)
    at ConfigChainBuilder.findConfigs (D:\workspace\iviewex\node_modules\babel-core\lib\transformation\file\options\build-config-chain.js:102:30)
    at buildConfigChain (D:\workspace\iviewex\node_modules\babel-core\lib\transformation\file\options\build-config-chain.js:61:13)
    at OptionManager.init (D:\workspace\iviewex\node_modules\babel-core\lib\transformation\file\options\option-manager.js:354:58)
    at File.initOptions (D:\workspace\iviewex\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (D:\workspace\iviewex\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (D:\workspace\iviewex\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (D:\workspace\iviewex\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (D:\workspace\iviewex\node_modules\babel-loader\lib\index.js:173:20)
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./node_modules/iview-loader??ref--2-1!./package/datepicker/datepickerAdapter.vue 27:12-37
 @ ./package/datepicker/datepickerAdapter.vue
 @ ./package/datepicker/index.js
 @ ./package/index.webpack.js
```

### What is the expected behavior?

It shouldn't include in package.json or include the config file in npm package.

**Comment by kaskii** [comment]
Same thing with ESLint. `eslint.config` is missing from `.config` folder but `package.json` references to it.

`[Error - 12:10:54 PM] ESLint stack trace:
[Error - 12:10:54 PM] Error: Failed to load config "./.config/eslint.config" to extend from.
Referenced from: *********/node_modules/@popperjs/core/package.json
    at configMissingError (*********/node_modules/eslint/lib/cli-engine/config-array-factory.js:265:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (*********/node_modules/eslint/lib/cli-engine/config-array-factory.js:826:23)
    at ConfigArrayFactory._loadExtends (*********/node_modules/eslint/lib/cli-engine/config-array-factory.js:731:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (*********/node_modules/eslint/lib/cli-engine/config-array-factory.js:660:25)`

` "eslintConfig": {
    "extends": "./.config/eslint.config"
  },`

**Comment by FezVrasta** [comment]
Should we strip the rules from package.json or include the config?

**Comment by g1084164986** [comment]
> Should we strip the rules from package.json or include the config?

Yes, using .eslintrc.js may be a better choice, eslint will auto read the file when it exist, it will be better in this case.

**Comment by petr-ujezdsky** [comment]
Is it possible to suppress the eslint warnings until proper fix is released? I have tried to add `node_modules` to `.eslintignore` but it still produces those warnings. We have like bazillion of them in the CI log making it hard to read ;(

**Comment by TrySound** [comment]
Make sure CI see this eslintignore. By the way eslint v7 ignores node_modules by default.

**Comment by petr-ujezdsky** [comment]
Adding `node_modules` into `.eslintignore` does not help for webpack build chain. Only for `yarn eslint`.

But we have figured out hotfix - split webpack JS chain into 2 separate chains:

`webpack.config.js`:
```
rules: [
          {
            // node_modules - only babel, no eslint
            test: /\.(js|jsx)$/,
            include: [
              path.resolve(__dirname, 'node_modules')
            ],
            use: [
              {
                loader: 'babel-loader'
              }
            ]
          }, {
            // project files - babel + eslint
            test: /\.(js|jsx)$/,
            include: [
              path.resolve(__dirname, './your-project-root/')
            ],
            use: [
              {
                loader: 'babel-loader'
              }, {
                loader: 'eslint-loader'
              }
            ]
          }
        ]
```

**Comment by TrySound** [comment]
This is kinda proper fix. There is nothing to do with this package. Eslint should ignore all node_modules. Btw `exclude: /node_modules/` works too.

**Comment by FezVrasta** [comment]
@TrySound what about babel?

**Comment by petr-ujezdsky** [comment]
I presume the `exclude: /node_modules/` is defined per-rule but not per-loader, so the only way is the pipeline split as I have suggested?
