### ISSUE TITLE
Unable to get property 'toString' of undefined for node objects

### ISSUE THREAD

**Issue by gabskoro** [popperjs/popper-core#1159]
Hi guys, after I updated `@popperjs/core` from `v2.4.2` to `v.2.4.4` I started getting those weird errors on `IE11` and `Edge` about node object being empty in some cases. Unfortunately, can't reproduce it in my app :(

**Here is my Stacktrace**

![screenshot-app bugsnag com-2020 08 05-13_58_13](https://user-images.githubusercontent.com/2737390/89410363-e5f3aa80-d723-11ea-9b15-9da5791a3a8e.png)

Any thoughts?

**Comment by cb-eli** [comment]
Happened to me as well, a fix will be very appreciated.

**Comment by cb-eli** [comment]
Pinned to version 2.5.2 and everything is working.
The problem is in version 2.5.3

**Comment by gabskoro** [comment]
Tnx guys 👍🏻

**Comment by guillaume86** [comment]
I have a very similar error in IE11 (popper v2.6.0) but with a different stack trace:

```
TypeError: Unable to get property 'toString' of undefined or null reference
  at getWindow(./node_modules/@popperjs/core/lib/dom-utils/getWindow.js:5:3)
  at isHTMLElement(./node_modules/@popperjs/core/lib/dom-utils/instanceOf.js:15:3)
  at Anonymous function(./node_modules/@popperjs/core/lib/dom-utils/getOffsetParent.js:33:10)
  at getOffsetParent(./node_modules/@popperjs/core/lib/dom-utils/getOffsetParent.js:57:3)
  at Anonymous function(./node_modules/@popperjs/core/lib/dom-utils/getClippingRect.js:38:7)
  at getClippingRect(./node_modules/@popperjs/core/lib/dom-utils/getClippingRect.js:53:3)
  at detectOverflow(./node_modules/@popperjs/core/lib/utils/detectOverflow.js:34:7)
  at state(./node_modules/@popperjs/core/lib/modifiers/hide.js:32:7)
  at instance(./node_modules/@popperjs/core/lib/createPopper.js:183:13)
  at Anonymous function(./node_modules/@popperjs/core/lib/createPopper.js:196:11)
  at u(/v3/polyfill.min.js:3:44570)
  at tn(/v3/polyfill.min.js:3:46995)
  at resolve(./node_modules/@popperjs/core/lib/createPopper.js:195:9)
  at Anonymous function(./node_modules/@popperjs/core/lib/utils/debounce.js:8:11)
  at j(/v3/polyfill.min.js:3:46067)
  at u(/v3/polyfill.min.js:3:44570)
  at Anonymous function(/v3/polyfill.min.js:3:48448)
  at e(/v3/polyfill.min.js:3:44702)
  at r(./node_modules/@sentry/browser/esm/helpers.js:60:13)
```

Anyone seeing an objection to checking for undefined in the getWindow function? It does fix the issue in my case.

**Comment by guillaume86** [comment]
I have a very similar error (IE11) that didn't get fixed by the merged patch because the stacktrace is different but still end up at getWindow with a null or undefined node:

```
TypeError: Unable to get property 'toString' of undefined or null reference
  at getWindow(./node_modules/@popperjs/core/lib/dom-utils/getWindow.js:5:3)
  at isHTMLElement(./node_modules/@popperjs/core/lib/dom-utils/instanceOf.js:15:3)
  at Anonymous function(./node_modules/@popperjs/core/lib/dom-utils/getOffsetParent.js:33:10)
  at getOffsetParent(./node_modules/@popperjs/core/lib/dom-utils/getOffsetParent.js:57:3)
  at Anonymous function(./node_modules/@popperjs/core/lib/dom-utils/getClippingRect.js:38:7)
  at getClippingRect(./node_modules/@popperjs/core/lib/dom-utils/getClippingRect.js:53:3)
  at detectOverflow(./node_modules/@popperjs/core/lib/utils/detectOverflow.js:34:7)
  at state(./node_modules/@popperjs/core/lib/modifiers/hide.js:32:7)
  at instance(./node_modules/@popperjs/core/lib/createPopper.js:183:13)
  at Anonymous function(./node_modules/@popperjs/core/lib/createPopper.js:196:11)
  at u(/v3/polyfill.min.js:3:44570)
  at tn(/v3/polyfill.min.js:3:46995)
  at resolve(./node_modules/@popperjs/core/lib/createPopper.js:195:9)
  at Anonymous function(./node_modules/@popperjs/core/lib/utils/debounce.js:8:11)
  at j(/v3/polyfill.min.js:3:46067)
  at u(/v3/polyfill.min.js:3:44570)
  at Anonymous function(/v3/polyfill.min.js:3:48448)
  at e(/v3/polyfill.min.js:3:44702)
  at r(./node_modules/@sentry/browser/esm/helpers.js:60:13)
```

I checked the getWindow revision history and it was actually null/undefined safe in the past, changing that seem to be an unfortunate accident during some refactoring (see https://github.com/popperjs/popper-core/commit/2d2af36c2300e7322e225c94ed4d4c2871aea230#diff-ba8bc6714c2aea848ff3673562b3ddabccf64e7ac5f004625ead0a1e1355a328). 

From my testing simply adding a falsy check to getWindow seem to fix my issue as well, I will submit a pull request doing just that.
