### ISSUE TITLE
Install error with 2.8.1

### ISSUE THREAD

**Issue by webbpinner** [popperjs/popper-core#1250]
Was just doing an install and got this error:
```
$ npm i @popperjs/core

> @popperjs/core@2.8.1 postinstall .../node_modules/@popperjs/core
> husky install .config/husky

sh: husky: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! @popperjs/core@2.8.1 postinstall: `husky install .config/husky`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @popperjs/core@2.8.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     .../.npm/_logs/2021-02-20T19_12_22_194Z-debug.log
```

I noticed 2.8.1 had just been posted within the hour so I tried installing version 2.7.2 via:
```
npm i @popperjs/core@2.7.2
```
I saw no error with that command.

Cheers,
-W

**Comment by joseurena3** [comment]
Husky docs have a documented fix which is not in popper  

https://typicode.github.io/husky/#/
![image](https://user-images.githubusercontent.com/74935816/108606328-8be8c880-7387-11eb-869a-cc4c6e85b9bc.png)

**Comment by eusonlito** [comment]
Same here, and after install husky manualy, the error is `.git can't be found`.

```
$> git:(master) ✗ npm install 

npm ERR! code 127
npm ERR! path /var/www/resources/views/assets/node_modules/@popperjs/core
npm ERR! command failed
npm ERR! command sh -c husky install .config/husky
npm ERR! sh: 1: husky: not found

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/www/.npm/_logs/2021-02-20T19_27_12_709Z-debug.log

$> git:(master) ✗ npm install husky --save-dev

added 1 package, and audited 1231 packages in 2s

$> git:(master) ✗ npm install   

npm ERR! code 1
npm ERR! path /var/www/resources/views/assets/node_modules/@popperjs/core
npm ERR! command failed
npm ERR! command sh -c husky install .config/husky
npm ERR! /var/www/resources/views/assets/node_modules/husky/lib/commands/install.js:20
npm ERR!         throw new Error(".git can't be found");
npm ERR!         ^
npm ERR! 
npm ERR! Error: .git can't be found
npm ERR!     at Object.install (/var/www/resources/views/assets/node_modules/husky/lib/commands/install.js:20:15)
npm ERR!     at Object.<anonymous> (/var/www/resources/views/assets/node_modules/husky/lib/bin.js:43:19)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:999:30)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:863:32)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
npm ERR!     at internal/main/run_main_module.js:17:47

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/www/.npm/_logs/2021-02-20T19_29_14_868Z-debug.log
```

**Comment by maths22** [comment]
If you are using yarn, just add 
```
  "resolutions": {
    "@popperjs/core": "2.8.0"
  }
  ```
  to your package.json as a temporary workaround.

**Comment by tcstory** [comment]
meet same same problem in 2.11.3

**Comment by kle-pra** [comment]
Same problem as above,  updating 2.11.2 -> 2.11.3.

```
npm ERR! command failed
npm ERR! command sh -c husky install .config/husky
npm ERR! sh: 1: husky: not found
```

**Comment by atomiks** [comment]
Weird, the package.json is the _exact_ same as v2.11.2 with the exception of the version number. It has an underscore at the start so it shouldn't run, same as the previous version

<img width="1018" alt="Screen Shot 2022-03-14 at 7 07 06 pm" src="https://user-images.githubusercontent.com/22450188/158130379-3e4b0e0a-1525-4ecc-ba1a-54829ca0e6e3.png">

**Comment by csvan** [comment]
Seeing the same issue on 2.11.3, this should be reopened. It currently breaks installs completely, even if you add husky as a devdep

**Comment by atomiks** [comment]
The npm metadata somehow had no underscore despite the package.json having one. We've republished `v2.11.4` by using `prepare` (removing `postinstall`) now which Husky recommends, it should fix the issue.
